ko_fi: # Replace with a single Ko-fi username
custom: https://www.paypal.com/donate/?hosted_button_id=3RDP4TBKEVYUS
Bitcoin (BTC): bc1qj3fq7zu6jq8y6kxce48qpt2am7nw5jf54lachd
Ethereum (ETH): 0x906Fdb412cF1cC55A94eDcC6Cb4b4583046D57f2
Dogecoin (DOGE): DPGsD5sbHRHNYXXbkVkyTs8tTdL5HQwFqR
Litecoin (LTC): ltc1qkzvcc7w2lwq9d3360wxk0dj4hlj3jsdzusudl0
